#!/bin/bash

untracked=$(git ls-files --others --exclude-standard)
if [ -n "$untracked" ]; then
  fileList=$(echo "$untracked" | tr '\n' ' ')
  echo "Untracked files found. Deleting ..."
  rm $fileList
  echo "Deleted: $fileList"
else
  echo "No untracked files found."
fi